steps:
- id: build
  uses: docker://ivotron/pandoc:2.3.1
  runs: [
    "pandoc/entrypoint.sh",
    "--standalone",
    "--metadata=monofont-size:scriptsize",
    "--from=markdown+smart",
    "--output=report.pdf",
    "--highlight-style=tango",
    "--bibliography=refs.bib",
    "--metadata=documentclass:scrartcl",
    "--metadata=classoption:conference",
    "--csl=pandoc/IEEE.csl",    
    "--metadata=natbib:false",
    "--metadata=usedefaultspacing:false",
    "--metadata=numbersections:true",
    "--metadata=secPrefix:section",
    "--filter=pandoc/pandoc-tabularize.py",
    "--filter=pandoc-crossref",
    "--filter=pandoc-citeproc",
    "report.md"
  ]
